MAIN:
	g++ AStar.cpp main.cpp -L/usr/local/lib -lopencv_videostab -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_video -lopencv_imgproc -lopencv_core -std=c++11 -o MAIN.out


